apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tesis
    spec:
      containers:
      - name: tesis
        image: tesis:1
        ports:
        - containerPort: 5000